//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIDCWA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleUser
    {
        public byte Role { get; set; }
        public int User { get; set; }
    }
}
